"""Dated manufacturing research plus explicitly hypothetical camera planning."""
import base64,json

def render(root):
 if not (root/'simulations/resolution-demo.json').exists():return ''
 demo=json.loads((root/'simulations/resolution-demo.json').read_text())
 def pic(name,caption):
  b=base64.b64encode((root/'docs/assets'/name).read_bytes()).decode()
  return f'<figure><img src="data:image/png;base64,{b}" alt="{caption}"><figcaption>{caption}</figcaption></figure>'
 slots=[('Quarter','1.94 × 2.53','1.05 × 1.65','1.73',48,56,2000,3000),('Half width','1.94 × 5.12','1.05 × 4.24','4.46',56,72,4000,5000),('Half height','3.93 × 2.53','3.05 × 1.65','5.02',56,72,4000,5000),('Full','3.93 × 5.12','3.05 × 4.24','12.92',56,74,7000,8000)]
 table=''.join(f'<tr><th>{n}</th><td>{die}</td><td>{core}</td><td>{area}</td><td>{io} / {total}</td><td>${early:,} / ${standard:,}</td></tr>' for n,die,core,area,io,total,early,standard in slots)
 payload=json.dumps(demo)
 return f'''<section id="camera-plan"><div class="tag">Planning study · checked 14 September 2026</div><h2>Architecture overview</h2><p>The proposed system keeps the pixel array, row control, column readout, multiplexing and output buffer on the sensor die. A wire-bonded board supplies amplification, ADC, controller, power and optics. The 64 × 64 design below is a planning concept; the verified array remains 3 × 3.</p>
{pic('camera-floorplan-concept.png','Illustrative full-slot area reservation for a proposed 64 × 64 array. This is not GDS or a verified floorplan.')}
<pre><code>Light → 3T pixel → column readout / mux → output buffer → bond pad
      → board amplifier / ADC → MCU or FPGA → image</code></pre>
<h2>From nine pixels to an open monochrome camera</h2>
<p><b>Proposed direction: a 64 × 64 camera development module, with 32 × 32 as the lower-risk geometry fallback.</b> These are targets, not completed designs. First finish extraction on the verified 20 µm junction array and establish an optical packaging path. A modest-resolution, inspectable open sensor is a plausible education/research product; customer demand and saleable performance remain unproven.</p>
<h3>How much silicon does a slot buy?</h3>
<p>A slot buys repeated copies of one die design, not exclusive use of a wafer. Published Run 3 dimensions and default pad-ring allocations are below. Prices are USD per batch of 1,000 dies, early-bird / standard. Core dimensions already exclude the default pad ring; readout circuits still share that core with the pixels.</p>
<div style="overflow-x:auto"><table><tr><th>Slot</th><th>Die (mm)</th><th>Core (mm)</th><th>Core mm²</th><th>I/O / total pads</th><th>Batch prices</th></tr>{table}</table></div>
<p>Sources: <a href="https://www.crowdsupply.com/wafer-space/gf180mcu-run-3/">Run 3 campaign</a> and <a href="https://mith.ro/gf180mcu-project-template/">standard slot specifications</a>. Full-die area is approximately 20.1 mm²; the core is only 12.92 mm². Published rounded die areas differ slightly between pages; the final run template must control the actual layout.</p>
<p>The published schedule lists early-bird pricing through September 30, purchase by December 9, GDS by December 16, 2026, and shipment in Q2 2027. The campaign funding widget shows a different closing date, and the homepage contains conflicting countdown messages. Treat these as planning dates and confirm the operative submission deadline and checkout price directly before ordering. <a href="https://wafer.space/">wafer.space schedule</a>.</p>
<h3>What resolution fits our design?</h3>
<p><b>Junction size is not pixel pitch.</b> Our 20 × 20 µm detector currently lives inside an 80 × 50 µm repeating cell. The estimates below are our geometry arithmetic; they exclude extra edge clearance and do not establish DRC, extraction or readout feasibility.</p>
<table><tr><th>Array</th><th>Pixels</th><th>Pitch</th><th>Array footprint</th><th>Assessment against full default core</th></tr>
<tr><th>32 × 32</th><td>1,024</td><td>80 × 50 µm, current</td><td>2.56 × 1.60 mm</td><td>Room for a first readout design; candidate fallback</td></tr>
<tr><th>64 × 64</th><td>4,096</td><td>80 × 50 µm, current</td><td>5.12 × 3.20 mm</td><td>Does not fit</td></tr>
<tr><th>64 × 64</th><td>4,096</td><td>40 × 40 µm, proposed</td><td>2.56 × 2.56 mm</td><td>Promising area budget; requires a new compact pixel</td></tr>
<tr><th>96 × 96</th><td>9,216</td><td>30 × 30 µm, hypothetical</td><td>2.88 × 2.88 mm</td><td>Tight side margin; a later optimization study</td></tr>
<tr><th>128 × 128</th><td>16,384</td><td>30 × 30 µm, hypothetical</td><td>3.84 × 3.84 mm</td><td>Does not fit</td></tr></table>
<p>A 64² array at 40 µm pitch occupies 6.55 mm², leaving about 6.37 mm² of the full core for row control, column circuitry, output buffering, references and test structures. This retains a 20 µm detector with a nominal 25% drawn junction fraction, if that compact cell can be routed and verified. A 128² array would need a pitch below 23.8 µm merely to fit the 3.05 mm core width, before side circuitry; that is smaller than our present 26 µm optical fill-clearance box. Megapixel imaging is not a realistic target for this detector and slot.</p>

<p>The half-height slot may support a smaller or more rectangular camera; the quarter slot is attractive for a detector/test-chip iteration. Select the slot after the pad ring and readout fit, not from array area alone.</p>
<h3>Wire bonding and the amplifier/ADC connections</h3>
<p>Put row sequencing and column multiplexing on the die so a camera does not require a separate bond for every row and column. A candidate signal path is:</p><pre><code>photodiode + 3T pixel → column bias / sample circuitry → column mux
→ output buffer → analog bond pad → board amplifier / ADC → MCU or FPGA</code></pre>
<p>External amplification and ADC are sensible for a first module, but we still need a driver able to charge pad, wire, PCB and ADC input capacitance. Provide clocks, reset, serial configuration and frame/line timing on digital pads. Budget analog connections for output, references/biases and test access, plus appropriate supply/ground pads and protection. Plan several optional analog test connections before freezing the pad map.</p>
<p>The standard full-slot template has <b>only two analog I/Os</b>; most of its 56 signal I/Os are digital. Two analog pads could be consumed by output and reference alone. Exposing more biases or test nodes needs a reviewed pad-ring configuration and assembly agreement, or internal generation of those signals. <a href="https://mith.ro/gf180mcu-project-template/">Pad-type breakdown</a>. The PDK I/O library lists roughly 350 × 75 µm pad cells and 60 × 60 µm bond openings; a small square of metal is not the whole pad/protection footprint. <a href="https://gf180mcu-pdk.readthedocs.io/en/latest/IPs/IO/gf180mcu_fd_io/features.html">GF180 I/O dimensions</a>.</p>
<p><b>Packaging needs attention before tapeout.</b> The documented COB process applies protective epoxy over the die and wire bonds. That is not evidence of an optical-window service. Request an exposed sensing area or suitable windowed/cavity package, with bond loops clear of the light path, controlled cleanliness and a lens mount. Confirm passivation/optical-stack restrictions as well as the package: removing dummy metal alone does not characterize optical response. <a href="https://www.crowdsupply.com/wafer-space/gf180mcu-run-2/updates/chip-on-board-packaging-progress">wafer.space packaging process</a>. The listed $1,500 COB add-on requires the default ring; custom optical assembly needs its own agreement and quote. <a href="https://wafer.space/">Packaging offer</a>.</p>
<h3>ADC speed: ADS1115 versus a camera readout</h3>
<p>64² at a target 10 frames/s needs at least 40,960 conversions/s for one sample per pixel, or 81,920 for two. Blanking and settling add overhead. A roughly 200 kS/s ADC budget is a starting requirement to investigate, not a verified frame rate or selected part. Two samples do not automatically give true correlated noise cancellation in this 3T architecture.</p>
<p>The <a href="https://www.ti.com/product/ADS1115">ADS1115</a> tops out at 860 conversions/s total. Ignoring all overhead, that is only 0.21 frames/s for 64² with one sample per pixel (about 4.8 seconds/frame), or half that rate for two samples. It remains useful for slow detector measurements, but choose a faster ADC class for a video-like module.</p>
<h3>How many cameras could be sold?</h3>
<p>With one sensor per die, a 1,000-die batch gives at most 1,000 sensor candidates—not 1,000 tested cameras and not evidence of 1,000 buyers. Putting multiple arrays on one die does not create separately packaged chips; further subdivision would require an agreed dicing/seal/pad plan. Packaging, electrical and optical acceptance, reserves and failures reduce the sellable count. A systematic first-silicon fault could leave no saleable units.</p>
<pre><code>Saleable units = floor(delivered dies × combined pass rate) − retained units</code></pre>
<table><tr><th>Hypothetical combined pass rate</th><th>Retained for engineering / replacements</th><th>Available units</th></tr><tr><td>50%</td><td>50</td><td>450</td></tr><tr><td>75%</td><td>50</td><td>700</td></tr><tr><td>90%</td><td>50</td><td>850</td></tr></table>
<p>These percentages are scenarios, not yield forecasts. At 700 available modules, a $7,000 fabrication bill alone allocates $10 per available module. Add optical packaging/bonding, PCB, amplifier/ADC/controller, lens, test fixtures and test time, assembly, shipping, taxes/duties, support, development labor and a possible second silicon run. We do not yet have supplier quotes or a defensible selling price.</p>
<p>For a small business, start with a clearly scoped open camera development kit and measure images from real silicon before promising image quality or delivery quantities. Kickstarter requires a working hardware prototype demonstrating the promised functions; these illustrative pictures are not campaign evidence of a working sensor. <a href="https://updates.kickstarter.com/how-to-launch-a-product-on-kickstarter-part-1-creating-your-prototype-and-manufacturing-plan/">Kickstarter prototype guidance</a>. Successful campaigns also pay a 5% platform fee plus roughly 3–5% processing. <a href="https://updates.kickstarter.com/kickstarter-fees-a-comprehensive-guide-for-creators/">Kickstarter fees</a>. Entity, tax and sales obligations depend on where you operate and sell; those decisions need your jurisdiction and professional advice.</p>
<h3>Recommended sequence</h3><ol><li>Finish extraction of the 20 µm array and compare to the existing scan.</li><li>Confirm optical-process and packaging feasibility; draft the actual pad map.</li><li>Lay out one compact 40 µm pixel, reverify it, and test a small multiplexed array with realistic output loads.</li><li>Choose 32² fallback versus 64² target from verified area, settling and signal results; integrate pad ring, control and test structures.</li><li>After fabrication, characterize dark current, responsivity, noise, bad pixels, uniformity and image capture on a wire-bonded board. Use measured yield and assembly quotes to plan sales.</li></ol></section>
<section id="resolution-demo"><h2>The same monochrome scene at increasing resolutions</h2>
<p>One AI-generated source scene is averaged into each sampling grid in linear light, then displayed in grayscale. Exposure, scene and field of view stay fixed. Large blocks are enlarged sensor samples, not extra detail. This uses square sample cells; our current 80 × 50 µm pitch is rectangular. It omits lens blur, noise, dead pixels, fill-factor effects and the GF180 optical response, and does not imply all shown resolutions fit our die.</p>
<label for="resolution-slider"><b>Choose resolution:</b></label> <input id="resolution-slider" type="range" min="0" max="7" value="4" step="1" style="width:min(65%,440px)"><output id="resolution-label" for="resolution-slider"></output>
<div style="max-width:650px;margin:16px auto"><canvas id="resolution-canvas" width="512" height="512" style="width:100%;height:auto" aria-label="Same scene at the selected resolution"></canvas></div>
{pic('resolution-comparison.png','Static comparison: 3, 8, 16, 32, 64, 96, 128 and 256 pixels per side, alongside the synthetic source.')}
<p>All versions show grayscale levels; “black and white” here means monochrome, not one-bit black/white thresholding. To regenerate: <code>bash scripts/run-tools.sh python3 scripts/camera-planning-visuals.py</code>, then rebuild the notebook.</p>
<script>(function(){{const data={payload}; const slider=document.getElementById('resolution-slider');const canvas=document.getElementById('resolution-canvas');const ctx=canvas.getContext('2d');function draw(){{const n=data.sizes[Number(slider.value)];const raw=atob(data.frames_gray8_base64[String(n)]);const tiny=document.createElement('canvas');tiny.width=tiny.height=n;const tc=tiny.getContext('2d');const im=tc.createImageData(n,n);for(let i=0;i<n*n;i++){{const v=raw.charCodeAt(i);im.data[4*i]=im.data[4*i+1]=im.data[4*i+2]=v;im.data[4*i+3]=255;}}tc.putImageData(im,0,0);ctx.imageSmoothingEnabled=false;ctx.drawImage(tiny,0,0,512,512);document.getElementById('resolution-label').textContent=` ${{n}} × ${{n}} — ${{(n*n).toLocaleString()}} pixels`;}}slider.addEventListener('input',draw);draw();}})();</script></section>'''
