"""Additional report sections, loaded by build-overview.py."""
import json,base64
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

def render(root):
 path=root/'simulations/repeatability.json'
 if not path.exists():return ''
 runs={r['name']:r for r in json.loads(path.read_text())}
 a=runs['low_reset'];b=runs['low_reset_fine'];c=runs['low_reset_finer']
 def difference(a,b):return max(abs(x-y)*1e6 for ra,rb in zip(a['rows'],b['rows']) for x,y in zip(ra['samples_V'],rb['samples_V']))
 assert difference(a,b)<100 and difference(b,c)<100
 assert all(row['last5_span_uV']<100 for row in c['rows'])
 fig,axs=plt.subplots(1,2,figsize=(11,4.5),layout='constrained')
 for name,label in [('baseline','3.3 V / 20 us'),('long_reset','3.3 V / 100 us'),('low_reset_finer','2.0 V / 20 us')]:
  r=runs[name];ys=np.array(r['rows'][0]['samples_V']);axs[0].plot(range(1,21),(ys-ys[0])*1000,'.-',label=label)
 for row,label in zip(c['rows'],['Dark','1 pA','5 pA']):axs[1].plot(range(1,21),row['samples_V'],'.-',label=label)
 for ax in axs:ax.set(xlabel='Cycle');ax.grid(alpha=.2);ax.legend(fontsize=9)
 axs[0].set(title='Dark reset memory',ylabel='Change from first sample (mV)')
 axs[1].set(title='2.0 V reset candidate',ylabel='Sampled column voltage (V)')
 plot=root/'docs/assets/repeatability.png';fig.savefig(plot,dpi=160);plt.close(fig)
 uri='data:image/png;base64,'+base64.b64encode(plot.read_bytes()).decode()
 shot=root/'docs/assets/xschem-reset-candidate.png'
 capture='<figure><img alt="Xschem screenshot of separate 2.0 V reset candidate" src="data:image/png;base64,'+base64.b64encode(shot.read_bytes()).decode()+'"><figcaption>Separate reset-candidate schematic; the original experiment remains available.</figcaption></figure>' if shot.exists() else ''
 rows=''
 for name in ['baseline','long_reset','mid_reset','low_reset_finer']:
  r=runs[name];rows+=f"<tr><td>{r['reset_V']:.1f} V / {r['reset_us']} µs</td><td>{r['step_us']} µs</td>"+''.join(f"<td>{x['last5_span_uV']:.3f}</td>" for x in r['rows'])+'</tr>'
 # Only claim checks when their actual result logs are present and successful.
 probe=root/'build/layout-probe-verified'
 verified=(probe/'magic.log').exists() and 'PROBE_DRC_COUNT=0' in (probe/'magic.log').read_text() and (probe/'lvs.log').exists() and 'Circuits match uniquely' in (probe/'lvs.log').read_text()
 status='Zero Magic DRC errors; Netgen reports a unique LVS match.' if verified else 'Not verified in this workspace: rerun the probe script.'
 return f'''<section id="repeatability"><div class="tag" style="color:#146379">Latest investigation · repeatability</div><h2>A more decisive reset</h2><p>We ran 20 cycles per condition, holding the reset-to-sample interval at 950 µs. Increasing the reset pulse from 20 to 100 µs also increases the cycle period from 1.00 to 1.08 ms, so the light-integration interval stays fixed.</p><p>Longer reset at 3.3 V does not eliminate dark history dependence. Lowering the reset drain supply to 2.0 V, while keeping the gate pulse and source-follower supply at 3.3 V, produces much more repeatable samples in this model.</p><p>The physical interpretation is that the NMOS retains more gate-to-source overdrive at a lower reset target. It can charge the node more decisively instead of creeping toward a threshold-limited level. The price is reduced signal swing and readout headroom. This is a design hypothesis supported by electrical simulation, not a fabricated-device result.</p><figure><img src="{uri}" alt="Twenty-cycle dark reset memory comparison and improved-reset output samples"><figcaption>Left: change from each run's first dark sample. Right: absolute samples using the finest timestep for the 2.0 V reset candidate. Different reset supplies shift the operating point.</figcaption></figure><h3>Spread of the final five samples</h3><p>Values below are max minus min in µV. Our provisional deterministic repeatability criterion is less than 100 µV; it is an engineering test threshold, not an ADC/noise requirement.</p><table><tr><th>Reset supply / pulse</th><th>Time step</th><th>Dark / µV</th><th>1 pA / µV</th><th>5 pA / µV</th></tr>{rows}</table><p>The finest-step 2.0 V run passes for all three light levels. Very small printed spreads can be below the simulator export resolution; they do not imply noiseless silicon. Startup cycles differ from the eventual repeated state, so a startup policy still needs to be defined.</p><h3>We checked numerical repeatability too</h3><p>The original numerical settings gave roughly 6 mV disagreement between 1 µs and 0.2 µs sampling steps. Tight charge tolerances initially caused a timestep failure at reset release. The accepted run uses Gear integration, chgtol=1e-18 C, trtol=1, reltol=1e-5, abstol=1e-16 A and gmin=1e-17 S.</p><p>Across all 20 samples and all three light levels, the maximum difference is <b>{difference(a,b):.2f} µV</b> for 1 → 0.2 µs and <b>{difference(b,c):.2f} µV</b> for 0.2 → 0.05 µs. These pass the provisional 100 µV numerical criterion. They do not establish convergence across every integration method or physical model.</p><p>The revised schematic is <code>xschem/pixel_reset_candidate.sch</code>. Earlier schematics and four-cycle results remain as historical experiments. The reset study still uses assumed diode capacitance, zero MOS diffusion areas, an ideal reset supply, and a passive column resistor. Junction geometry, corners and noise remain outstanding.</p>{capture}<pre><code>bash scripts/simulate-cycles.sh
bash scripts/run-tools.sh python3 scripts/check-repeatability.py
bash scripts/simulate-reset-candidate.sh
bash scripts/check-layout-probe.sh
bash scripts/run-tools.sh python3 scripts/build-overview.py</code></pre></section>
<section id="array"><div class="tag" style="color:#146379">Next physical target</div><h2>A 3 × 3 array, with real shared wiring</h2><p>Three reset lines, three row-select lines, three column outputs, shared ground, 3.3 V VDD and a separate reset supply. Select only one row at a time and read all three columns. The first deliverable is a connected core with labeled ports; ADC, pad ring, package and optical assembly come later.</p><table><tr><th>Reset + select</th><th>COL0</th><th>COL1</th><th>COL2</th></tr><tr><th>RST0 / ROW0</th><td>Pixel 0,0</td><td>Pixel 0,1</td><td>Pixel 0,2</td></tr><tr><th>RST1 / ROW1</th><td>Pixel 1,0</td><td>Pixel 1,1</td><td>Pixel 1,2</td></tr><tr><th>RST2 / ROW2</th><td>Pixel 2,0</td><td>Pixel 2,1</td><td>Pixel 2,2</td></tr></table><p class="small">Target connectivity diagram, not a completed layout or array simulation.</p><h3>First verification step completed</h3><p><b>{status}</b> The test is a single GF180 NMOS, W=1 µm and L=0.5 µm, generated in Magic, exported to GDS and extracted. An independently written four-terminal reference netlist is used for LVS. This is not pixel or array signoff.</p><p>The first minimum-length geometry had metal-rule errors. Relaxing the length, widening guard clearance and enlarging gate landing pads resolved the probe's errors. The electrical pixel has not yet adopted these geometries.</p><ol><li><b>Diode probe:</b> verify a recognized junction, its electrical parameters and extraction.</li><li><b>Single pixel:</b> connect three MOSFETs and one physical diode; pass DRC/LVS and rerun with actual junction geometry.</li><li><b>Array:</b> use gdsfactory to assemble and route nine checked pixels; run full core DRC and LVS.</li><li><b>Extracted operation:</b> simulate row scanning, column load, reset repeatability and a known 3×3 illumination pattern.</li></ol><p>Array LVS must account for all <b>27 MOSFETs and nine diodes</b>, distinguish every row/reset net, and prove shared column connectivity. It must not pass by black-boxing pixels or omitting the physical diode. Optical current sources belong only to simulation.</p><p>The installed Magic technology explicitly recognizes an N+/substrate diode. The old prototype's n-well/substrate diode needs a demonstrated extraction path before reuse. Choosing a supported junction is not an optical-performance guarantee.</p><p>Gdsfactory 9.44.0, Magic, Netgen and GF180 rule files are installed. The old <code>gf180mcu</code> Python import is unavailable. Checked PDK-generated GDS can be imported into gdsfactory for placement and routing. See <code>layout/README.md</code> for the acceptance criteria and remaining work.</p><p class="note">No 3×3 layout exists yet. Zero errors on this transistor probe are only a local Magic check; final manufacturing requires the applicable full-rule, density, antenna/ERC and shuttle checks.</p></section>'''
