"""Latest notebook milestone: verified 3x3 physical array."""
import base64,json,hashlib
import numpy as np
import matplotlib.pyplot as plt

def render(root):
 if not (root/'simulations/array-verification.json').exists():return ''
 checks=json.loads((root/'simulations/array-verification.json').read_text())
 results=json.loads((root/'simulations/array-results.json').read_text())
 assert checks['gds_sha256']==hashlib.sha256((root/'build/array_3x3.gds').read_bytes()).hexdigest(),'Report does not match the current GDS'
 assert checks['magic_drc_errors']==0 and checks['klayout_total']==0
 wave=np.loadtxt(root/'build/array-sim/wave.txt',skiprows=1)
 fig,axes=plt.subplots(2,1,figsize=(11,6),sharex=True,layout='constrained')
 for col in range(3):
  axes[0].plot(wave[:,0]*1000,wave[:,col+1],label=f'ROW{col}')
  axes[1].plot(wave[:,0]*1000,wave[:,col+4],label=f'COL{col}')
 for ax in axes:ax.legend(ncol=3);ax.grid(alpha=.2);ax.set_ylabel('Voltage (V)')
 axes[0].set_title('Three rows, selected one at a time')
 axes[1].set_title('Three column outputs across three frames');axes[1].set_xlabel('Time (ms)')
 fig.savefig(root/'docs/assets/array-scan.png',dpi=150);plt.close(fig)
 def picture(name,alt,caption):
  path=root/'docs/assets'/name
  if not path.exists():return ''
  src='data:image/png;base64,'+base64.b64encode(path.read_bytes()).decode()
  return f'<figure><img src="{src}" alt="{alt}"><figcaption>{caption}</figcaption></figure>'
 frames=results['frames_V'];last=frames[-1]
 rows=''.join('<tr><th>Row '+str(i)+'</th>'+''.join(f'<td>{v:.6f} V</td>' for v in row)+'</tr>' for i,row in enumerate(last))
 return f'''<section id="verified-array"><div class="tag" style="color:#146379">Latest milestone · connected layout and readout</div><h2>The 3 × 3 array is built and verified.</h2><div class="grid"><div class="card"><strong>0 DRC errors</strong>Magic and the installed full GF180MCUD KLayout deck.</div><div class="card"><strong>LVS matches</strong>Independent reference and the graphical Xschem schematic.</div><div class="card"><strong>27 MOS + 9 diodes</strong>Counted through the extracted hierarchy; pixels are not black boxes.</div></div><p>Gdsfactory assembles nine physical pixels and routes shared reset, select, supply and column nets. The checked artifact is <code>build/array_3x3.gds</code>. DRC and extraction read this GDS back into the verification tools.</p><p>Each pixel contains three W=1 µm / L=0.5 µm GF180 NMOS devices and a 5 × 5 µm N+/substrate diode. Its center has no contact array or overlying routed/dummy metal; one small cathode contact sits near an edge. Optical response is still uncharacterized.</p>
<h3 id="photosensitive-area">Where is the light-sensitive area?</h3>
{picture('array-photosensitive-annotated.png','Nine small photodiode junctions outlined in cyan, with the larger surrounding fill clearance marked separately','Annotated illustration of the layout screenshot. Cyan marks the nine drawn photodiode junctions. AI-assisted annotation is explanatory; use the original GDS views below for exact geometry.')}
<p>Each cyan square marks a <b>5 × 5 µm N+/substrate junction (25 µm²)</b>, one per pixel. This is the intended light detector. The larger dark region surrounds it with clearance from routing and dummy fill; the fill generator excludes an 11 × 11 µm box around each diode center. That clearance does not increase the drawn junction area. A small cathode contact remains near the junction edge.</p>
<p>At the current 80 × 50 µm pixel pitch, the drawn junction occupies <b>0.625% of the pixel area</b>, before contact shadowing. This spacious prototype prioritizes connectivity and verification. The effective optical collection area and sensitivity still need characterization; the drawing alone does not establish those values or a manufactured optical opening.</p>
<h3 id="diode-size-tradeoffs">Why are the detectors small—and should we enlarge them?</h3>
<p><b>Yes, we can make the photodiodes larger.</b> The cyan square is only the detector; a complete pixel also contains three transistors and wiring. Our detector is 5 × 5 µm inside an 80 × 50 µm pixel cell. The mismatch is a consequence of this first, spacious electrical-verification layout. The 5 µm size is a prototype choice, not an optical optimum or a demonstrated GF180 maximum. Most of the dense pattern in the screenshot is dummy fill, which serves manufacturing density rules rather than collecting light.</p>
<p>Increasing the detector within the same pixel pitch increases the geometric light-collecting fraction without changing the nine-pixel image resolution. Increasing the entire pixel pitch instead makes the array larger; on a fixed-size die it leaves room for fewer pixels. Compacting the transistor wiring is another way to improve the collecting fraction.</p>
<table><tr><th>Square junction</th><th>Drawn area</th><th>Area relative to present</th><th>Fraction of an 80 × 50 µm cell</th></tr><tr><td>5 × 5 µm (current)</td><td>25 µm²</td><td>1×</td><td>0.625%</td></tr><tr><td>10 × 10 µm (candidate)</td><td>100 µm²</td><td>4×</td><td>2.5%</td></tr><tr><td>20 × 20 µm (candidate)</td><td>400 µm²</td><td>16×</td><td>10%</td></tr></table>
<p>These are geometric comparisons. The completed size study above now records layout verification and electrical results for these variants; the fractions are not measured sensitivity gains. Larger variants require repositioning contacts and guard rings, expanding fill clearances and moving nearby routes, followed by fresh density checks, DRC and LVS.</p>
<h4>The main tradeoff: more collected charge, but more capacitance</h4>
<p>With uniform illumination and comparable collection efficiency, a larger junction generally collects more photoelectrons during an exposure. More collected electrons can improve photon-shot-noise-limited signal-to-noise ratio. However, in our <b>3-transistor pixel the diode is also the voltage-sensing node</b>. Enlarging it increases junction capacitance, so each electron produces a smaller voltage change. The useful first-order relationship is:</p>
<pre><code>Voltage change ≈ photocurrent × exposure time / total sense-node capacitance
Conversion gain ≈ electron charge / total sense-node capacitance</code></pre>
<p>If both photocurrent and capacitance rise by roughly four times, the voltage change at the same illumination and exposure stays roughly similar—not four times larger. Real capacitance includes area, perimeter, transistors and wiring, and varies with voltage. Holding the simulated current fixed while enlarging the diode would test charge-to-voltage conversion, not equal illumination.</p>
<ul><li><b>Potential benefits:</b> more collected photons and, for the same usable voltage swing, greater charge capacity before saturation.</li><li><b>Costs to check:</b> lower voltage per electron, increased reset charging time, and potentially more dark current. Overall noise and dynamic range depend on the full readout circuit.</li><li><b>Optical limits:</b> metal shading, surface layers, wavelength and carrier collection still matter. More drawn area alone does not guarantee a proportional sensitivity improvement.</li></ul>
<p><b>Size-study plan (now completed above):</b> retain the verified 5 µm baseline and compare 10 µm and 20 µm variants. Use the same assumed illumination per unit area, exposure and readout conditions; update diode area/perimeter and parasitics for each. Compare signal swing, saturation, reset completion and settling. Those results will guide sizing; optical characterization is still needed to choose a final camera pixel.</p>
<p>Background: <a href="https://www.cs.rochester.edu/courses/572/fall2022/decks/lect10-sensor-basics.pdf">Yuhao Zhu, Image Sensor Basics</a> (also saved in this docs folder). The dimensions and candidate table above are specific to this repository; the size-study section above contains their completed local verification results.</p>
{picture('array-functional.png','Functional wiring of the nine-pixel layout before dummy fill','Functional geometry before fill, shown to make wiring visible. Pixel pitch is 80 × 50 µm: deliberately spacious for inspection, not an optimized camera pixel.')}
<details><summary>View the final filled GDS and the physical pixel</summary>
{picture('array-layout.png','Final filled 3x3 layout with nine protected optical windows','Final verified GDS including floating dummy fill. The nine dark windows protect the diode regions from added metal and poly fill.')}
{picture('pixel-layout.png','Physical diode and three transistors in one routed pixel','Single-pixel functional layout, before die-density fill. Three transistors sit to the left of the diode; layer-separated routes connect them.')}
</details><h3>What changed from the original layout script?</h3><p>The original <code>test.py</code> remains unchanged. It used the old <code>gf180mcu</code> Python package, an n-well diode and a 300 × 500 instantiation. That package is unavailable in the container. The new <code>layout/array_3x3.py</code> uses installed gdsfactory 9.44.0, importing checked PDK-generated primitive GDS and adding explicit metal/via routing.</p><p>No new host virtual environment or tools were needed. Magic, Netgen, KLayout, Xschem, ngspice and the PDK run in the existing pinned Docker image. The N+/substrate diode replaces the earlier n-well junction to use a verified extraction path; this is a detector-structure change, not a claim of equivalent optical performance.</p><h3>DRC and LVS evidence</h3><ul><li>Magic DRC: zero errors after checking the delivered GDS.</li><li>KLayout: zero violations with <code>variant=gf180mcuD</code> and the installed full rule deck, including density checks.</li><li>Netgen: unique match against an independently written hierarchy and against <code>xschem/array_3x3.sch</code>.</li><li>Physical diode extraction: area=25 µm², perimeter=20 µm. No optical current sources or ideal capacitance placeholders in layout.</li></ul><p>Initial runs found gate-contact clearances, database-unit and density issues. Contact placement was corrected; the GDS now uses a 1 nm database unit while the drawn geometry stays on the intended manufacturing grid. Isolated poly/metal fill was added with optical keepouts. Top-metal fill uses the required larger spacing. LVS was repeated after fill to confirm functional connectivity.</p><details><summary>Artifact fingerprint</summary><p>SHA-256 of the verified GDS:</p><pre><code>{checks['gds_sha256']}</code></pre><p>Machine-readable results: <code>simulations/array-verification.json</code>. Full logs and extracted netlists: <code>build/array-check/</code>. A rebuilt artifact needs refreshed verification; the report builder checks this fingerprint.</p></details></section>
<section id="array-operation"><h2>The schematic scans a known 3 × 3 pattern</h2>
{picture('xschem-array.png','Xschem view of three rows and three column buses','Actual Xschem capture. Each block opens into the physical three-transistor/one-diode schematic. Supply and control labels connect shared nets.')}
<p>The transient testbench supplies synthetic photocurrents in pA:</p><table><tr><th></th><th>Column 0</th><th>Column 1</th><th>Column 2</th></tr><tr><th>Row 0</th><td>0</td><td>5</td><td>15</td></tr><tr><th>Row 1</th><td>15</td><td>0</td><td>5</td></tr><tr><th>Row 2</th><td>5</td><td>15</td><td>0</td></tr></table><p>Each row receives a 20 µs reset pulse. Its readout starts 920 µs after reset rises, and we sample at 970 µs. Row starts are separated by 1 ms and repeat every 3 ms. Only one row is selected at a time. The 3 ms test period is not a measured camera frame-rate specification.</p>
{picture('array-scan.png','Row-select controls and three output voltage traces over three frames','Outputs are meaningful during the selected row’s read interval. Column loads remain external 1 MΩ resistors and assumed 1 pF capacitors.')}
<h3>Third-frame samples</h3><table><tr><th></th><th>COL0</th><th>COL1</th><th>COL2</th></tr>{rows}</table><p>The three brightness levels appear in the intended locations. The largest change between corresponding samples in frames 2 and 3 is <b>{results['max_frame2_to3_change_V']*1e6:.2f} µV</b>. This is deterministic model repeatability, not measured noise.</p><p>A retained earlier test at 0/10/50 pA saturated the brightest pixels near ground. The 0/5/15 pA run stays within the readout range. Both results are stored; the acceptable photocurrent range still requires systematic characterization.</p><p class="note">These traces use the LVS-matched schematic with GF180 MOS junction geometry and the GF180 electrical diode model. Optical currents are assumed. Extracted wiring/fill capacitance, resistance, optical efficiency, noise, mismatch and packaging effects are not included yet.</p></section>
<section><h2>Reproduce this milestone</h2><pre><code># Generate the inspectable hierarchy (already present in the repo):
python3 scripts/make-array-schematics.py
# Build GDS, run Magic + KLayout DRC and both LVS comparisons,
# verify all device counts, simulate and render:
bash scripts/verify-array.sh
# Update the offline notebook:
bash scripts/run-tools.sh python3 scripts/build-overview.py</code></pre><p>The verification script fails if either DRC result is nonzero, either LVS comparison fails, or the device count differs from 27 MOSFETs and nine diodes. Simulation checks finite waveforms, non-overlapping row selects and brightness ordering in every row.</p><h3>Next: extracted readout and manufacturing integration</h3><p>The next electrical task is parasitic extraction, including fill coupling, followed by the same scan and settling checks. Then we can reduce the very generous pixel pitch and decide on column bias, output buffers, ADC interface, pads and protection. The diode response, optical openings and package need confirmation for the intended manufacturing run.</p><p>These are successful local core checks against the installed GF180MCUD tools. They are not wafer.space submission approval or a claim that this is a complete, packaged camera.</p></section>'''
